web:
  image: nginx
  volumes:
   - nginx:/etc/nginx/conf.d/mysite.template
  ports:
   - "80:80"
  environment:
   - NGINX_HOST=HOST IP
   - NGINX_PORT=80
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/ > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
volumes:
    nginx: